=== sjetty/Test/conf/application/configuration.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--Generated by Turbo XML 2.3.1.100. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
	 elementFormDefault = "qualified">
	<xsd:element name = "configuration">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "attribute" minOccurs = "0" maxOccurs = "unbounded"/>
				<xsd:element ref = "configuration" minOccurs = "0" maxOccurs = "unbounded"/>
				<xsd:element ref = "configuration-file" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "attribute">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "type"/>
				<xsd:element ref = "value"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "name" type = "xsd:string"/>
	<xsd:element name = "type">
		<xsd:simpleType>
			<xsd:list>
				<xsd:simpleType>
					<xsd:restriction base = "xsd:string">
						<xsd:enumeration value = "java.lang.String"/>
						<xsd:enumeration value = "java.lang.Boolean"/>
						<xsd:enumeration value = "java.lang.Integer"/>
						<xsd:enumeration value = "java.lang.Double"/>
						<xsd:enumeration value = "java.lang.Long"/>
						<xsd:enumeration value = "java.lang.Float"/>
						<xsd:enumeration value = "com.momentumsystems.lang.EncryptedString"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:list>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name = "value" type = "xsd:string"/>
	<xsd:element name = "configuration-file">
		<xsd:complexType>
			<xsd:attribute name = "fileName" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== sjetty/Test/conf/application/database.eeoc95dev.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<configuration xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "configuration.xsd">
	<name>database</name>
	<attribute>
		<name>default</name>
		<type>java.lang.String</type>
		<value>NVS</value>
	</attribute>
        <attribute>
		<name>livelink</name>
		<type>java.lang.String</type>
		<value>NVSLivelink</value>
	</attribute>

    <configuration>
		<name>NVS</name>
		<attribute>
			<name>driver</name>
			<type>java.lang.String</type>
            <value>oracle.jdbc.driver.OracleDriver</value>
		</attribute>
		<attribute>
			<name>url</name>
			<type>java.lang.String</type>
			<value>jdbc:oracle:thin:@eeoc95dev:1521:eeocdev</value>
		</attribute>
		<attribute>
			<name>user</name>
			<type>java.lang.String</type>
            <value>cts_o</value>
			<!--<value>eeoccts_o1</value>-->
		</attribute>
		<attribute>
			<name>password</name>
			<type>java.lang.String</type>
			<value>ctsoeeoc</value>
		</attribute>
        <attribute>
			<name>dialect</name>
			<type>java.lang.String</type>
			<value>net.sf.hibernate.dialect.Oracle9Dialect</value>
		</attribute>
        <attribute>
			<name>showSql</name>
			<type>java.lang.String</type>
			<value>true</value>
		</attribute>
	</configuration>
        <configuration>
		<name>NVSLivelink</name>
		<attribute>
			<name>driver</name>
			<type>java.lang.String</type>
            <value>oracle.jdbc.driver.OracleDriver</value>
		</attribute>
		<attribute>
			<name>url</name>
			<type>java.lang.String</type>
			<value>jdbc:oracle:thin:@eeoc95dev:1521:eeocdev</value>
		</attribute>
		<attribute>
			<name>user</name>
			<type>java.lang.String</type>
			<!--<value>eeoclivelink1</value>-->
            <value>livelink</value>
		</attribute>
		<attribute>
			<name>password</name>
			<type>java.lang.String</type>
			<value>CTSLIVELINK</value>
		</attribute>
        <attribute>
			<name>dialect</name>
			<type>java.lang.String</type>
			<value>net.sf.hibernate.dialect.Oracle9Dialect</value>
		</attribute>
        <attribute>
			<name>showSql</name>
			<type>java.lang.String</type>
			<value>true</value>
		</attribute>
	</configuration>
</configuration>

=== sjetty/Test/conf/application/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configuration.xsd">
	<name>overall</name>
	<configuration>
      <name>Application</name>
      <configuration-file fileName="cts.xml" />
    </configuration>
    <configuration>
		<name>Connection</name>
		<configuration-file fileName="livelink.xml"/>
        <configuration-file fileName="database.xml" />
    </configuration>
    <configuration>
      <name>EMail</name>
      <configuration-file fileName="mailer.xml" />
    </configuration>
    <configuration>
		<name>Logon Filter</name>
		<attribute>
			<name>Cookie Name</name>
			<type>java.lang.String</type>
			<value>EEOCLivelink</value>
		</attribute>
	</configuration>
    <configuration>
        <name>URL Macro Decoder</name>
        <attribute>
            <name>Livelink Decoder</name>
            <type>java.lang.String</type>
            <value>com.momentumsystems.livelink.util.URLMacroDecoder</value>
        </attribute>
    </configuration>
	<configuration-file fileName="implementationFactory.xml"/>
</configuration>

=== sjetty/Test/conf/application/implementationFactory.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configuration.xsd">
	<name>Implementation Factory</name>
	<configuration>
		<name>mappings</name>
		<attribute>
			<name>default</name>
			<type>java.lang.String</type>
			<value>remote</value>
		</attribute>
		<attribute>
			<name>client</name>
			<type>java.lang.String</type>
			<value>remote</value>
		</attribute>
		<attribute>
			<name>webapp</name>
			<type>java.lang.String</type>
			<value>remote</value>
		</attribute>
		<attribute>
			<name>ejbclient</name>
			<type>java.lang.String</type>
			<value>local</value>
		</attribute>
		<attribute>
			<name>ejbserver</name>
			<type>java.lang.String</type>
			<value>server</value>
		</attribute>
	</configuration>
	<attribute>
		<name>com.momentumsystems.logon.LogonFilterDecoder</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.logon.LogonFilterDecoder</value>
	</attribute>
	<attribute>
		<name>com.momentumsystems.util.crypt.Decryptor</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.util.crypt.ROT13</value>
	</attribute>
	<attribute>
		<name>com.momentumsystems.util.crypt.Encryptor</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.util.crypt.ROT13</value>
	</attribute>
	<attribute>
		<name>com.momentumsystems.logon.UserInformationFactory</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.livelink.logon.UserInformationFactory</value>
	</attribute>
	<attribute>
		<name>com.momentumsystems.logon.LogonFilterDecoder</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.logon.ClearTextDecoder</value>
	</attribute>
	<attribute>
		<name>com.momentumsystems.livelink.SessionTool</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.livelink.server.SessionTool</value>
	</attribute>
	<attribute>
		<name>com.momentumsystems.livelink.FolderTool</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.livelink.server.FolderTool</value>
	</attribute>
	<attribute>
		<name>com.momentumsystems.livelink.NodeTool</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.livelink.server.NodeToolServer</value>
	</attribute>
	<attribute>
		<name>com.momentumsystems.livelink.WorkflowTool</name>
		<type>java.lang.String</type>
		<value>com.momentumsystems.livelink.server.WorkflowTool</value>
	</attribute>
</configuration>

=== sjetty/Test/conf/application/database.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<configuration xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "configuration.xsd">
	<name>database</name>
	<attribute>
		<name>default</name>
		<type>java.lang.String</type>
		<value>CTS</value>
	</attribute>
        <attribute>
		<name>livelink</name>
		<type>java.lang.String</type>
		<value>CTSLivelink</value>
	</attribute>

    <configuration>
		<name>CTS</name>
		<attribute>
			<name>driver</name>
			<type>java.lang.String</type>
            <value>oracle.jdbc.driver.OracleDriver</value>
		</attribute>
		<attribute>
			<name>url</name>
			<type>java.lang.String</type>
			<value>jdbc:oracle:thin:@10.0.0.79:1521:orcldev1</value>
		</attribute>
		<attribute>
			<name>user</name>
			<type>java.lang.String</type>
			<value>eeoccts_o1</value>
		</attribute>
		<attribute>
			<name>password</name>
			<type>java.lang.String</type>
			<value>ctsoeeoc</value>
		</attribute>
        <attribute>
			<name>dialect</name>
			<type>java.lang.String</type>
			<value>net.sf.hibernate.dialect.Oracle9Dialect</value>
		</attribute>
        <attribute>
			<name>showSql</name>
			<type>java.lang.String</type>
			<value>true</value>
		</attribute>
	</configuration>
        <configuration>
		<name>CTSLivelink</name>
		<attribute>
			<name>driver</name>
			<type>java.lang.String</type>
            <value>oracle.jdbc.driver.OracleDriver</value>
		</attribute>
		<attribute>
			<name>url</name>
			<type>java.lang.String</type>
			<value>jdbc:oracle:thin:@10.0.0.79:1521:orcldev1</value>
		</attribute>
		<attribute>
			<name>user</name>
			<type>java.lang.String</type>
            <value>eeoclivelink1</value>
		</attribute>
		<attribute>
			<name>password</name>
			<type>java.lang.String</type>
			<value>CTSLIVELINK</value>
		</attribute>
        <attribute>
			<name>dialect</name>
			<type>java.lang.String</type>
			<value>net.sf.hibernate.dialect.Oracle9Dialect</value>
		</attribute>
        <attribute>
			<name>showSql</name>
			<type>java.lang.String</type>
			<value>true</value>
		</attribute>
	</configuration>
</configuration>

=== sjetty/Test/conf/application/livelink.dmstp2.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configuration.xsd">
	<name>Livelink</name>
	<attribute>
		<name>default</name>
		<type>java.lang.String</type>
		<value>dev</value>
	</attribute>

    <!--  This section may be overridden in the application.properties file in the classpath -->
    
    <configuration>
		<name>dev</name>
		<attribute>
			<name>host</name>
			<type>java.lang.String</type>
			<value>201.1.24.84</value>
		</attribute>
		<attribute>
			<name>port</name>
			<type>java.lang.Integer</type>
			<value>2099</value>
		</attribute>
		<attribute>
			<name>dftConnection</name>
			<type>java.lang.String</type>
			<value></value>
		</attribute>
		<attribute>
			<name>user</name>
			<type>java.lang.String</type>
			<value>Admin</value>
		</attribute>
		<attribute>
			<name>password</name>
			<type>com.momentumsystems.lang.EncryptedString</type>
			<value>ll4cts=good</value>
		</attribute>
		<attribute>
			<name>baseURL</name>
			<type>java.lang.String</type>
            <value>http://201.1.24.84/livelink/livelink.exe</value>
		</attribute>
		<attribute>
			<name>supportURL</name>
			<type>java.lang.String</type>
            <value>http://201.1.24.84/support</value>
		</attribute>


        <attribute>
            <name>userCacheTimeout</name>
            <type>java.lang.Integer</type>
            <value>-1</value>
        </attribute>

        <attribute>
            <name>userCacheCapacity</name>
            <type>java.lang.Integer</type>
            <value>15000</value>
        </attribute>

        <attribute>
            <name>groupCacheTimeout</name>
            <type>java.lang.Integer</type>
            <value>-1</value>
        </attribute>

        <attribute>
            <name>groupCacheCapacity</name>
            <type>java.lang.Integer</type>
            <value>15000</value>
        </attribute>

    </configuration>

</configuration>

=== sjetty/Test/conf/application/livelink.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configuration.xsd">
	<name>Livelink</name>
	<attribute>
		<name>default</name>
		<type>java.lang.String</type>
		<value>dev</value>
	</attribute>

    <!--  This section may be overridden in the application.properties file in the classpath -->
    
    <configuration>
		<name>dev</name>
		<attribute>
			<name>host</name>
			<type>java.lang.String</type>
			<value>eeoc95dev.momentumsystems.com</value>
		</attribute>
		<attribute>
			<name>port</name>
			<type>java.lang.Integer</type>
			<value>2099</value>
		</attribute>
		<attribute>
			<name>dftConnection</name>
			<type>java.lang.String</type>
			<value>ctslivelink</value>
		</attribute>
		<attribute>
			<name>user</name>
			<type>java.lang.String</type>
			<value>Admin</value>
		</attribute>
		<attribute>
			<name>password</name>
			<type>com.momentumsystems.lang.EncryptedString</type>
			<value>eeoc</value>
		</attribute>
		<attribute>
			<name>baseURL</name>
			<type>java.lang.String</type>
            <value>http://eeoc95dev.momentumsystems.com/livelink/livelink.exe</value>
		</attribute>
		<attribute>
			<name>supportURL</name>
			<type>java.lang.String</type>
            <value>http://eeoc95dev.momentumsystems.com/livelinksupport</value>
		</attribute>


        <attribute>
            <name>userCacheTimeout</name>
            <type>java.lang.Integer</type>
            <value>-1</value>
        </attribute>

        <attribute>
            <name>userCacheCapacity</name>
            <type>java.lang.Integer</type>
            <value>15000</value>
        </attribute>

        <attribute>
            <name>groupCacheTimeout</name>
            <type>java.lang.Integer</type>
            <value>-1</value>
        </attribute>

        <attribute>
            <name>groupCacheCapacity</name>
            <type>java.lang.Integer</type>
            <value>15000</value>
        </attribute>

    </configuration>

</configuration>

=== sjetty/Test/conf/application/mailer.mosys34.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<configuration xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "configuration.xsd">
  <name>Mailer</name>
      <attribute>
          <name>mail.smtp.host</name>
          <type>java.lang.String</type>
          <value>w8kexchange.momentumsystems.com</value>
      </attribute>
      <attribute>
          <name>mail.from</name>
          <type>java.lang.String</type>
          <value>xlu@MomentumSystems.com</value>
      </attribute>
      <attribute>
          <name>mail.replyto</name>
          <type>java.lang.String</type>
          <value>xlu@MomentumSystems.com</value>
      </attribute>
       <attribute>
          <name>mail.test.to</name>
          <type>java.lang.String</type>
          <value>xlu@MomentumSystems.com</value>
      </attribute>
      <attribute>
          <name>mail.test.activate</name>
          <type>java.lang.Boolean</type>
          <value>TRUE</value>
      </attribute>
</configuration>
